### ISSUE TITLE
dixi-0.6.0.3 build failure with the new base-orphans-0.5.0

### ISSUE THREAD

**Issue by DanBurton** [liamoc/dixi#13]
Note this can only happen with the `old-base` flag set to `False`, which leaves base-orphans unconstrained. `base-orphans` is required by some of dixi's dependencies, so it is brought into the compilation process either way.

```
Dixi/Database/Orphans.hs:33:1:
    Duplicate instance declarations:
      instance Foldable Last -- Defined at Dixi/Database/Orphans.hs:33:1
      instance Foldable Last
        -- Defined in ‘base-orphans-0.5.0:Data.Orphans’

Dixi/Database/Orphans.hs:34:1:
    Duplicate instance declarations:
      instance Traversable Last
        -- Defined at Dixi/Database/Orphans.hs:34:1
      instance Traversable Last
        -- Defined in ‘base-orphans-0.5.0:Data.Orphans’

Dixi/Database/Orphans.hs:39:1:
    Duplicate instance declarations:
      instance Data a => Data (Last a)
        -- Defined at Dixi/Database/Orphans.hs:39:1
      instance Data a => Data (Last a)
        -- Defined in ‘base-orphans-0.5.0:Data.Orphans’
```

Saw this on the 2016-01-18 nightly stackage build, reproduced locally.
Also seen here: http://matrix.hackage.haskell.org/package/dixi#GHC-7.10/dixi-0.6.0.3

**Comment by RyanGlScott** [comment]
Nice find – I'm surprised I didn't find this when I did a search of Hackage for pre-existing orphan instances. I'll file a pull request.
